name: 'List'
multiple: FALSE
category: 'Médiathèque'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        id: "vactory_mediatheque_list"
        resource: node--vactory_mediatheque
        filters:
          - fields[node--vactory_mediatheque]=drupal_internal__nid,path,title,field_mediatheque_date,field_vactory_excerpt,field_vactory_media,field_mediatheque_theme,field_vactory_tags,field_mediatheque_type,field_mediatheque_video,field_vactory_media_document
          - fields[taxonomy_term--mediatheque_theme_albums]=tid,name
          - fields[taxonomy_term--mediatheque_types]=tid,name
          - fields[taxonomy_term--tags]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[media--remote_video]=name,field_media_oembed_video
          - fields[media--file]=name,field_media_file
          - fields[file--image]=filename,uri
          - fields[file--document]=filename,uri
          - include=field_vactory_tags,field_mediatheque_theme,field_mediatheque_type,field_vactory_media_document,field_vactory_media_document.field_media_file,field_mediatheque_video,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=6
          - sort[sort-vactory-date][path]=field_mediatheque_date
          - sort[sort-vactory-date][direction]=DESC
          - filter[status][value]=1
        vocabularies:
          mediatheque_types: mediatheque_types
          mediatheque_theme_albums: mediatheque_theme_albums
          medium_year: medium_year
          tags: tags