name: 'Tabs'
multiple: FALSE
category: 'Gouvernance'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  views:
    type: dynamic_views
    label: 'Views'
    options:
      '#required': TRUE
      '#default_value':
        views_id: vactory_governance
        views_display_id: block_tabs
        fields:
          id: id
          uuid: key
          title: title
          url: url
          field_vactory_taxonomy_1: role
          field_vactory_media: image
        vocabularies:
          vactory_governance_role: vactory_governance_role
  link:
    type: url_extended
    label: 'Lien'
