name: 'Two Columns'
multiple: FALSE
category: 'Press Release'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  views:
    type: dynamic_views
    label: 'Views'
    options:
      '#required': TRUE
      '#default_value':
        views_id: vactory_press_release
        views_display_id: block_two_columns
        fields:
          id: id
          uuid: key
          title: title
          url: url
          field_vactory_excerpt: excerpt
          field_press_release_theme: category
          field_vactory_media: image
          field_vactory_document: file
  link:
    type: url_extended
    label: 'Lien'
