name: 'List'
multiple: FALSE
category: 'Events'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--vactory_event
        filters:
          - fields[node--vactory_event]=drupal_internal__nid,path,title,field_vactory_taxonomy_1,field_vactory_taxonomy_2,field_vactory_media,field_vactory_excerpt
          - fields[taxonomy_term--vactory_event_category]=tid,name
          - fields[taxonomy_term--vactory_event_citys]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - include=field_vactory_taxonomy_1,field_vactory_taxonomy_2,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=9
          - sort=-created
          - filter[status][value]=1
        vocabularies:
          vactory_event_category: vactory_event_category
          vactory_event_citys: vactory_event_citys
