name: 'List'
multiple: FALSE
category: 'Testimonials'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        id: "vactory_testimonials_list"
        resource: node--vactory_testimonials
        filters:
          - fields[node--vactory_testimonials]=drupal_internal__nid,path,title,field_vactory_address,body,field_vactory_date,field_vactory_excerpt,field_vactory_media,field_vactory_profils,field_vactory_role,field_vactory_tags,is_flagged,has_flag
          - fields[taxonomy_term--vactory_testimonials_profils]=tid,name
          - fields[taxonomy_term--tags]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - include=field_vactory_profils,field_vactory_tags,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=9
          - sort[sort-vactory-date][path]=field_vactory_date
          - sort[sort-vactory-date][direction]=DESC
          - filter[status][value]=1
        vocabularies:
          vactory_testimonials_profils: vactory_testimonials_profils
          tags: tags