name: 'Header - Default'
multiple: TRUE
category: 'Headers'
enabled: TRUE
fields:
  cta:
      type: url_extended
      label: 'Add extra button'
extra_fields:
  header_logo:
      type: image
      label: "Header's logo"
  show_language_dropdown:
      type: checkbox
      label: "Display language dropdown"
  show_account:
      type: checkbox
      label: "Enable account button"
  use_menu:
      type: text
      label: "Menu ID"
      options:
        '#description': 'Menu machine name. Default to main'
