name: 'List'
multiple: FALSE
category: 'Publication'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--vactory_publication
        filters:
          - fields[node--vactory_publication]=drupal_internal__nid,path,title,field_vactory_date,field_vactory_document,field_vactory_call_to_action,field_vactory_excerpt,field_vactory_media,field_vactory_publication_theme
          - fields[taxonomy_term--vactory_publication_theme]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - fields[file--document]=filename,uri
          - include=field_vactory_publication_theme,field_vactory_document,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=9
          - sort=-created
          - filter[status][value]=1
        vocabularies:
          vactory_publication_theme: vactory_publication_theme

#  views:
#    type: dynamic_views
#    label: 'Views'
#    options:
#      '#required': TRUE
#      '#default_value':
#        views_id: vactory_publication
#        views_display_id: block_list
#        fields:
#          id: id
#          uuid: key
#          title: title
#          url: url
#          field_vactory_excerpt: excerpt
#          field_vactory_publication_theme: category
#          field_vactory_media: image
#          field_vactory_document: file
#          field_vactory_date: date
#        vocabularies:
#          vactory_publication_theme: vactory_publication_theme
