name: '15 - Froala - Content Left Text With CTA & Background Image'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Background'
    options:
      '#required': TRUE
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  btn:
    type: checkbox
    label: 'Activer le style btn-primary'
  touch:
    type: checkbox
    label: 'Ajouter touch decoration a haut de block'
  mode:
    type: checkbox
    label: 'Activer le mode invers√© (Description To Right)'
