name: "Reset your password"
multiple: FALSE
category: 'Espace priv√©'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  intro:
    type: text_format
    label: 'Introduction'
    options:
      '#format': 'full_html'