name: '90 - Froala - Features 3 Blocks Title, Description & CTA'
multiple: TRUE
category: 'Froala'
enabled: TRUE
limit: 3
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenÃªtre'
