name: 'Cross content news'
multiple: FALSE
category: 'Cross Content'
enabled: TRUE
fields:
  title:
    type: text
    label: "title"
  intro:
    type: text_format
    label: "Introduction"
    options:
      "#format": full_html
  collection:
    type: json_api_cross_content
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--vactory_news
        filters:
          - fields[node--vactory_news]=drupal_internal__nid,path,title,field_vactory_news_theme,field_vactory_media,field_vactory_excerpt,field_vactory_date,is_flagged,has_flag
          - fields[taxonomy_term--vactory_news_theme]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - include=field_vactory_news_theme,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=3
          - sort[sort-vactory-date][path]=field_vactory_date
          - sort[sort-vactory-date][direction]=DESC
          - filter[status][value]=1
  link:
    type: url_extended
    label: "Link"
