name: 'Two Columns'
multiple: FALSE
category: 'Blog'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--vactory_blog
        filters:
          - fields[node--vactory_blog]=drupal_internal__nid,path,title,field_blog_category,field_vactory_excerpt,field_blog_tags,field_vactory_media
          - fields[taxonomy_term--vactory_blog_categories]=tid,name
          - fields[taxonomy_term--vactory_blog_tags]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - include=field_blog_category,field_blog_tags,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=2
          - sort=-created
          - filter[status][value]=1
  link:
    type: url_extended
    label: 'Lien'
